# Generated by Django 3.1.5 on 2021-01-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210113_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
